services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - simple_net

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - simple_net
      
    environment:
      POSTGRES_PASSWORD: test

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:5050
      - 80:80
    networks:
      - simple_net

    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234

networks:
  simple_net:
    driver: bridge